#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright 2024 Greg Kroah-Hartman <gregkh@linuxfoundation.org>
#
# Given a git commit id, see if it has been reverted in the tree anywhere
#
# Relies on the sql database to be present.

REAL_SCRIPT=$(realpath -e "${BASH_SOURCE[0]}")
SCRIPT_TOP="${SCRIPT_TOP:-$(dirname "${REAL_SCRIPT}")}"

# Location of our database.  Should be initialized already.
DB="${SCRIPT_TOP}"/commits.db

id=$1

if [ "${id}" == "" ] ; then
        echo "$0 ID_TO_FIND"
        exit 1
fi

revert=$(sqlite3 commits.db "SELECT id FROM commits WHERE reverts='${id}';")
if [[ "${revert}" != "" ]] ; then
	echo "commit ${id} is reverted by commit ${revert}"
fi

exit 0
